### ISSUE TITLE
Add new Covid API

### ISSUE THREAD

**Issue by monacook** [monacook/Covid.Tracker#5]
Add new Covid API
- [x] Add new API from RapidAPI
- [x] Make sure that Auth is set
- [x] populate the data onto the rows

Time estimateed: 2 hrs
actual: 3.5hrs
