### ISSUE TITLE
Refactor API

### ISSUE THREAD

**Issue by monacook** [monacook/Covid.Tracker#7]
- [ ] Add a new api folder
- [ ] Add api file and place the api as its own component
- [ ] Add PropTypes
- [ ] Pass down props from api
